openapi: '3.0.2'
info:
  title: Angry cat videos
  contact:
    name: Any cat productions
    email: Angrycats@cats.com
    url: www.cats.com/angrycatvideos/support
  description: This api displays cat videos of very angry cats. Pacificsts should avoid these videos
  license:
    name: Angry cat videos license
    url: https://opensource-cats.com/license
  termsOfService: https://opensource-cats.com/termsofLicense
  version: '1.0'
servers:
  - url: https://api-{env}.cats.com/videos
    description: Cat server
    variables:
      env:
        default: "prod"
        enum:
          - "prod"
          - "uat"
          - "dev"
          - "demo"
paths:
  /v1/angry-cats:
    get:
      summary: List of angry cat videos which are not sutiable for pacifists
      description: Returns a list of videos in which viscous and lethal acts are performed by angry cats
      tags:
        - Violent Videos
      parameters:
        - name: violence-level
          in: query
          schema:
            type: string
            enum:
              - "graphic"
              - "endOfTheWorld"
              - "girlFight"
          example: "endOfTheWorld"
          description: choose your poison             
      responses:
        '200':
          description: Returns a list of videos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    url:
                      type: string
                    description:
                      type: string
                    summary:
                      type: string
                  required:
                    - url

  /v1/angry-cats/{cat-id}:
    get:
      summary: Get video with a particular cat-id
      description: Fetches a video based on cat-ids puchased by you
      parameters:
        - in: path
          name: cat-id
          schema:
            type: integer
          description: The ID of the cat
          required: true
          example: 101
      responses:
        '200':  
          description: Returns a video with requested Id.
          content:
            application/json:
              schema:
                type: object
                properties:
                  url:
                    type: string
                  description:
                    type: string
                  summary:
                    type: string
                required:
                  - url     
                    