openapi: 3.1.0
info:
  title: Enhanced Sample API with OAuth and Webhook
  version: 1.0.0
paths:
  /pets:
    summary: Pet API Operations
    description: Operations related to pets in the pet store
    get:
      summary: List all pets
      description: Retrieves a list of all pets in the store.
      security:
        - OAuth2: ['read:pets']
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              examples:
                example1:
                  value: 
                    - id: 1
                      name: Fido
                      age: 5
                    - id: 2
                      name: Kitty
                      age: 2
components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1  # Minimum value constraint
        name:
          type: string
        age:
          type: integer
          minimum: 0  # Minimum age constraint
        animal_type:
          type: string
      if:
        properties:
          animal_type:
            const: "Cat"
      then:
        required:
          - breed
        properties:
          breed:
            type: string
      else:
        properties:
          color:
            type: string
  securitySchemes:
    OAuth2:  # OAuth 2.0 Security Scheme
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read:pets: Read pets information
webhooks:  # Webhook details
  petAdded:
    post:
      summary: A pet was added
      description: Triggered when a new pet is added to the store
      responses:
        '200':
          description: Webhook received successfully
